
export const href = {
  url: {
    implementation_thresholding: "https://github.com/123mpozzi/nbrancati",
    implementation_statistical: "https://github.com/123mpozzi/skin-statistical",
    implementation_unet: "https://github.com/123mpozzi/skinny",
  },
  img: {
    intro_ori: require('@site/static/img/skin_det_ori3.webp').default,
    intro_skin: require('@site/static/img/skin_det_red3.webp').default,
    applications_facial: require('@site/static/img/applications_facial_analysis.webp').default,
    applications_ads: require('@site/static/img/applications_ads.webp').default,
    applications_biomedical: require('@site/static/img/applications_biomedical.webp').default,
    limitations_clay: require('@site/static/img/clay.webp').default,
    limitations_wood: require('@site/static/img/wood.webp').default,
    limitations_lighting1: require('@site/static/img/lighting_1.webp').default,
    limitations_lighting2: require('@site/static/img/lighting_2.webp').default,
    approach_svg: '/img/methodological-approach-vert.svg',
    approach_horiz_svg: '/img/methodological-approach.svg',
    octocat_svg: '/img/octocat.svg',
    thresh_trapeziaparams: require('@site/static/img/trapezia_params.webp').default,
    stat_histogram_ori: require('@site/static/img/skin_det_ori3.webp').default,
    stat_histogram_res: require('@site/static/img/3d_hist.webp').default,
    stat_math_probability_svg: '/img/probability.svg',
    stat_math_threshold_svg: '/img/probability_thresh.svg',
    unet_architecture: require('@site/static/img/skinny_arch.webp').default,
    unet_inception1: require('@site/static/img/inception1.webp').default,
    unet_inception2: require('@site/static/img/inception2.webp').default,
    unet_inception3: require('@site/static/img/inception3.webp').default,
    unet_denseblock_svg: '/img/dense.svg',
    results_singles: require('@site/static/img/results_singles.webp').default,
    results_cross: require('@site/static/img/results_cross.webp').default,
    results_singletones: require('@site/static/img/results_singletones.webp').default,
    results_crosstones: require('@site/static/img/results_crosstones.webp').default,
    tooltip_dprs_svg: '/img/dprs.svg',
  },
  doc: {
    thesis: require('@site/static/doc/human-skin-detection-in-color-images.pdf').default,
  },
}
